from .troycon import TroyConClient
from .constants import ( 
    SERVER_IP_ADDR, SERVER_PORT_NUM,CURRENT_SCRIPT_DIR, 
    TEST_DIRECTORY, RECONNECTION_DELAY_SECONDS
)

__all__ = ["TroyConClient",(SERVER_IP_ADDR, SERVER_PORT_NUM, CURRENT_SCRIPT_DIR, TEST_DIRECTORY, RECONNECTION_DELAY_SECONDS)]
__version__ = "1.1.0"